# Generated by Django 5.1.7 on 2025-03-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinformation',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='username',
        ),
        migrations.AlterModelTable(
            name='otp',
            table='otp_codes',
        ),
    ]
