# Generated by Django 5.1.7 on 2025-04-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vote_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
