# Generated by Django 5.1.7 on 2025-04-22 16:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.course')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('video', models.FileField(upload_to='videos/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.chapter')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
