# Generated by Django 5.1.7 on 2025-04-25 12:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_course_total_duration_alter_course_table_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Tổng số câu hỏi')),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số bài học'),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Lệ phí'),
        ),
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='intro_videos/', verbose_name='Video giới thiệu'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='easy', max_length=10, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số người học'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số video'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link tài liệu'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên chương'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Tổng thời lượng'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(verbose_name='Thời lượng'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên bài học'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(verbose_name='Link video'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exercise', verbose_name='Bài tập'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('choices', models.JSONField(verbose_name='Các đáp án')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='Đáp án đúng')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Điểm')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.exercise')),
            ],
            options={
                'db_table': 'multiple_choice_question',
            },
        ),
    ]
