# Generated by Django 5.1.7 on 2025-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_course_qr_code_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Giới thiệu khóa học'),
        ),
    ]
