# Generated by Django 5.1.7 on 2025-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_course_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Mã QR'),
        ),
    ]
