# Generated by Django 5.1.7 on 2025-04-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_course_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='document_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='lesson_documents/', verbose_name='Tài liệu bài học'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/', verbose_name='Video bài học'),
        ),
    ]
