# Generated by Django 5.1.7 on 2025-04-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_lesson_document_link_lesson_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='document',
            new_name='document_link',
        ),
    ]
