# Generated by Django 5.1.7 on 2025-05-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_document_lesson_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('basic', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='basic', max_length=30, verbose_name='Trình độ'),
        ),
    ]
