# Generated by Django 5.1.7 on 2025-05-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_chapter_created_at_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Tổng điểm'),
        ),
        migrations.CreateModel(
            name='ExerciseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('answer_a', models.CharField(max_length=255, verbose_name='Đáp án A')),
                ('answer_b', models.CharField(max_length=255, verbose_name='Đáp án B')),
                ('answer_c', models.CharField(max_length=255, verbose_name='Đáp án C')),
                ('answer_d', models.CharField(max_length=255, verbose_name='Đáp án D')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='Đáp án đúng')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Điểm')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.exercise')),
            ],
            options={
                'db_table': 'exercise_question',
            },
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
    ]
