# Generated by Django 5.1.7 on 2025-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_exercise_total_score_exercisequestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercisequestion',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='lesson_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID bài học'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
