# Generated by Django 5.1.7 on 2025-05-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
