# Generated by Django 5.1.7 on 2025-05-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userinformation_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bounty_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
