# Generated by Django 5.1.7 on 2025-05-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_question_bounty_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='intro_video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link video giới thiệu'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link video bài học'),
        ),
    ]
