# Generated by Django 5.1.7 on 2025-05-20 01:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_course_intro_video_lessonviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonViewLog',
            new_name='LessonVideoView',
        ),
        migrations.AlterModelTable(
            name='lessonvideoview',
            table='lesson_video_view',
        ),
    ]
