# Generated by Django 5.1.7 on 2025-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_lessondocumentview'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments/', verbose_name='Tệp đính kèm'),
        ),
    ]
