# Generated by Django 5.1.7 on 2025-06-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_commentforanswer_commentforquestion_voteforanswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforanswer',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commentforquestion',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='voteforanswer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voteforquestion',
            options={'managed': False},
        ),
    ]
