# Generated by Django 5.1.7 on 2025-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_commentforanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_approve',
            field=models.SmallIntegerField(default=0, verbose_name='Duyệt câu trả lời'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approve',
            field=models.SmallIntegerField(default=0, verbose_name='Duyệt bình luận'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_approve',
            field=models.SmallIntegerField(default=0, verbose_name='Duyệt khóa học'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_approve',
            field=models.SmallIntegerField(default=0, verbose_name='Duyệt câu hỏi'),
        ),
    ]
