# Generated by Django 5.1.7 on 2025-06-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_answer_is_approve_comment_is_approve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforanswer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commentforquestion',
            options={'ordering': ['-created_at']},
        ),
    ]
