# Generated by Django 5.1.7 on 2025-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_commentforanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentforanswer',
            name='is_approve',
            field=models.SmallIntegerField(default=0, verbose_name='Duyệt bình luận câu trả lời'),
        ),
        migrations.AddField(
            model_name='commentforquestion',
            name='is_approve',
            field=models.SmallIntegerField(default=0, verbose_name='Duyệt bình luận câu hỏi'),
        ),
    ]
