# Generated by Django 5.1.7 on 2025-06-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_commentforanswer_is_approve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApproveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('question', 'Câu hỏi'), ('answer', 'Câu trả lời'), ('comment', 'Bình luận'), ('courses', 'Khóa học')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
