# Generated by Django 5.1.7 on 2025-06-24 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_autoapprovesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('point_change', models.IntegerField()),
                ('user_id_last_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
