# Generated by Django 5.1.7 on 2025-06-24 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_reputation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('min_reputation', models.IntegerField()),
                ('user_id_last_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
